# .streamlit/secrets.toml

# Replace with your account details
snowflake_user = "curtis_castro"
snowflake_password = "uvc2bta4bgk!bjc9AHQ"
snowflake_account = "YMB68310"      # e.g. xy12345.us-east-1
snowflake_warehouse = "COMPUTE_WH"
snowflake_database = "DEMO_STAGING"
snowflake_schema = "ENTERPRISE"
